- name: Provision EC2 Instance
  hosts: localhost
  gather_facts: False
  vars:
    region: "us-east-1"
    instance_type: "t3.micro"
    image: "ami-086dc92dc0617898a"     # Replace with your desired AMI ID
    security_group_id: "sg-0d5ba8190c1247d9f"  # Replace with your security group name
    

  tasks:
    - name: Launching instance
      amazon.aws.ec2:
         count: 1
         group_id: "{{ security_group_id }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         instance_tags:
          Name: ansible-createEC2
      register: ec2

    - name: Add instance to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: launched_instances
      with_items: "{{ ec2_instance.instances }}"

- name: Install bottle into the specified (virtualenv), inheriting globally installed modules
  ansible.builtin.pip:
      name:
        - boto3
        - botocore
      executable: pip3

- name: Configure EC2 Instances
  hosts: launched_instances
  become: yes
  gather_facts: True

  tasks:
    # Your configuration tasks for the newly provisioned EC2 instance go here.
    # For example, you can install packages, configure services, etc.
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started